### ISSUE TITLE
Converter phonemas para grafemas

### ISSUE THREAD

**Issue by Edresson** [alessandrobokan/PETRUS#1]
Olá, existe alguma maneira de converter os fonemas em grafemas ?
Preciso converter os grafemas em fonemas e após converter os fonemas em grafemas, isso é útil para síntese de voz e reconhecimento de voz ( Automatic Speech Recognition). 

Agradeço a atenção. 

Atenciosamente, Edresson Casanova.

**Comment by alessandrobokan** [comment]
Desculpa a demora em responder. O G2P é um conjunto de regras definidas exclusivamente para transformar grafema em fonema. Acredito que para converter fonema a grafema as regras devem mudar. Melhor consultar a linguista Vanessa Marquiafavel <marquiafavel@gmail.com>, ela foi quem criou todas as regras que eu codifiquei aqui :D.

Atte
